### PR TITLE
Built in web browser

### PR DESCRIPTION
**Pull request by fabiosoft**
Added built in web browser and additional button which points to a website.
Thanks to 0x0c who provided a basic web view controller.

### CODE REVIEW

**Comment by fouquet** [comment]
Basically a good idea,but I really don't like adding the whole browser class (especially not by adding it to the project; much better to make it a requirement in the Podspec). Too much can break over the course of iOS releases. It may also be preferable to open the URLs in an already existing in-app browser. I'd say it would be better to let the developer decide which browser to use, and add a delegate to RFAboutView to open URLs.

**Comment by fabiosoft** [comment]
Indeed, I added a new property called: BOOL webBuiltIn and a reference to the web controller. I used an already working web class so that made all quicker.
How do you recommend to edit the Podspec?

**Comment by fouquet** [comment]
You're referencing M2DWebViewController, so anyone adding this will be forced to use this specific class. That's why I'm saying it would be better to add a delegate with a method openURL:, and the delegate can choose what to do with it. If the delegate is nil, open it always with UIApplication. That would have the advantage that the dev implementing can choose how they show that URL _and_ we don't have the additional third-party dependency.

**Comment by fabiosoft** [comment]
Implemented delegate.
Let me know if you can merge now.

**Comment by fouquet** [comment]
Great! Thanks for your work! :)

**Pull request merged**
